#!/usr/bin/python3
# import stuff
import os
import sys
from config import *
from dategen import *
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# initialize webdriver
if(wdriver == "Firefox"):
    options = webdriver.FirefoxOptions()
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--incognito')
    options.add_argument('--headless')
    driver = webdriver.Firefox(service_log_path=os.path.devnull, options = options)
if(wdriver == "Chrome"):
    options = webdriver.ChromeOptions()
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--incognito')
    options.add_argument('--headless')
    driver = webdriver.Chrome(cdpath, options = options)

date = dateGen(ndays)
homework = []

# log into edupage
driver.get(website+"/login/")
username = driver.find_element_by_name("username")
password = driver.find_element_by_name("password")
username.send_keys(uname)
password.send_keys(passwd)
driver.find_element_by_xpath("//input[@type='submit']").click()

# parse retrieved homework
driver.get(website+"/exam/?")
time.sleep(1)

# select homework within date range
for i in range(len(date)):
    path = "//li[@data-date='"+date[i]+"']/div[@class='hwItemInner']/div[@class='hwCnt']/div[@class='hwTitle']"
    hw = driver.find_elements_by_xpath(path)
    for n in range(len(hw)):
        homework.append((hw[n].text, date[i]))

driver.quit()

# stdout homework
rows, columns = os.popen('stty size', 'r').read().split()
try:
    mode = str((sys.argv)[1])
except:
    mode = "--normal"
    
if(mode == "--minimal" or mode == "-m"):
    for i in range(len(homework)):
        print(homework[i][0] + " " + homework[i][1])
if(mode == "--normal"):
    print(separatorchar*int(columns))
    for i in range(len(homework)):
        print(homework[i][0] + "\n" + homework[i][1])
        print(separatorchar*int(columns))
if(mode == "--simple" or mode == "-s"):
    for i in range(len(homework)):
        print(homework[i][0] + "\n" + homework[i][1] + "\n")
