#!/usr/bin/python3
# import stuff
import os
import sys
from config import Config
import dategen as dg
from colors import *
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# initialize webdriver
if(Config.driver.lower() == "firefox"):
    options = webdriver.FirefoxOptions()
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--incognito')
    options.add_argument('--headless')
    driver = webdriver.Firefox(service_log_path=os.path.devnull, options = options)
elif(Config.driver.lower() == "chrome"):
    options = webdriver.ChromeOptions()
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--incognito')
    options.add_argument('--headless')
    driver = webdriver.Chrome(Config.chrome, options = options)

dates = dg.generate(Config.days)
homework = []

# log into edupage
driver.get(Config.provider+"/login/")
username = driver.find_element_by_name("username")
password = driver.find_element_by_name("password")
username.send_keys(Config.username)
password.send_keys(Config.password)
driver.find_element_by_xpath("//input[@type='submit']").click()

# parse retrieved homework
driver.get(Config.provider+"/exam/?")
time.sleep(1)

# select homework within date range
for date in dates:
    hwl = driver.find_elements_by_xpath(
        "//li[@data-date='"
        + date
        + "']/div[@class='hwItemInner']/div[@class='hwCnt']/div[@class='hwTitle']"
    )
    for hw in hwl:
        homework.append((hw.text, date))

driver.quit()

# stdout homework
try:
    mode = sys.argv[1]
except:
    mode = 0
    
if(mode == "--minimal" or mode == "-m"):
    for hw in homework:
        print(hw[0] + " " + hw[1])

elif(mode == "--formatted" or mode == "-f"):
    for hw in homework:
        title, body = hw[0].split(":", 1)
        snum = 0
        text = ""
        for char in body:
            if(char == " "):
                snum = snum + 1
            if(char == "\n"):
                char = ""
            if((snum % Config.Format.newline) == 0 and char == " "):
                char = "\n"
            text = text + char
            date = datetime.strptime(hw[1], "%Y-%m-%d").strftime(Config.Format.date[1])
        print(
            Config.Format.title + title + ", " + end + "due " + Config.Format.date[0] + date + end 
            + "\n" + text + "\n"
        )

else:
    for hw in homework:
        print(hw[0] + "\n" + hw[1] + "\n")
