#!/bin/sh

dir=$(pwd)
echo "Installing edupage-homework (eduhw)..."
if [ -d "/usr/share/eduhw" ]; then
  cp $dir/*.py /usr/share/eduhw/
  cp $dir/eduhw /usr/share/eduhw/
else
  mkdir /usr/share/eduhw
  cp $dir/*.py /usr/share/eduhw/
  cp $dir/eduhw /usr/share/eduhw/
fi
cd /usr/share/eduhw
rm config-example.py
cp $dir/.run/eduhw /usr/bin
