#!/bin/sh

dir=$(pwd)
echo "Installing edupage-homework (eduhw)..."
if [ -d "/usr/lib/eduhw" ]; then
  cp $dir/*.py /usr/lib/eduhw/
  cp $dir/eduhw /usr/lib/eduhw/
else
  mkdir /usr/lib/eduhw
  cp $dir/*.py /usr/lib/eduhw/
  cp $dir/eduhw /usr/lib/eduhw/
fi
cd /usr/lib/eduhw
rm config-example.py
cp $dir/bin/eduhw /usr/bin
